---
- block:
    - name: install incron
      yum:
        name: incron
        state: installed
    - name: start incrond
      service:
        name: incrond
        state: started
        enabled: true
    - name: copy incron config
      lineinfile:
        path: /var/spool/incron/root
        create: true
        line: >
          /app/shared/consul/
          IN_MOVED_TO,IN_CLOSE_WRITE,IN_DELETE
          (systemctl restart {{ app.value.consul.user.user }}-consul; date)
          >> /tmp/incrond.txt 2>&1"
        mode: 0644
  become: true
