- block:
  - name: install incron
    yum:
      name: incron
      state: installed
  - name: copy incron config
    lineinfile:
      path: /var/spool/incron/root
      create: True
      line: "/app/shared/consul/ IN_MOVED_TO,IN_CLOSE_WRITE,IN_DELETE (systemctl restart {{app.value.consul.user.user}}-consul; date) >> /tmp/incrond.txt 2>&1"
  become: True
