- debug:
    msg: "{{app}}"

- block:
  - name: install consul
    yum:
      name: consul
      state: installed
  - name: install dig
    yum:
      name: bind-utils
      state: installed
  become: True
  become_user: root

- block:
  - name: create consul dirs
    file:
      path: "{{app.value.consul.user.home}}/consul/{{item}}"
      state: directory
    loop:
    - conf
    - data
    - var
  become: True
  become_user: "{{app.value.consul.user.user}}"

- name: look for consul
  command: dig consul.service.consul +short
  register: _consul_servers
  changed_when: False
- set_fact:
    _need_bootstrap: "{{_consul_servers.stdout == ''}}"

- include_tasks: init.yml
  when: _need_bootstrap
  run_once: True
